name: Build
on:
  push:
    paths:
      - "!README.md"
      - "!LICENSE"
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ 386, amd64, arm, arm64 ]
        exclude:
        - os: darwin
          arch: 386
        - os: darwin
          arch: arm
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Build binary
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build .
